# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f9bbbbf52864a481f4f427ecde9893627bf908c619811cdb02bcf2a16e69ff12e94d49dfd20efaafc0d1b05ad14f4e43a472616ee75f9f607b91493e823593

test:
  secret_key_base: 2f40521a565c62d01f042433e7760458d4a426e77a24bc34cd759d4745d67481386fe1f8571ba9f20b048bacdfccf7079f5f9d190295fc05e03ba9b965cf3199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
